import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import { ViewTransitions } from 'next-view-transitions';

import ForceDarkMode from '@/components/auto-theme-switcher';
import PrivyProviderComp from '@/components/providers/privy-provider';
import { ThemeProvider } from '@/components/providers/theme-provider';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en" suppressHydrationWarning>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem={false}
            disableTransitionOnChange
          >
            <ForceDarkMode />
            <PrivyProviderComp>{children}</PrivyProviderComp>
          </ThemeProvider>
        </body>
      </html>
    </ViewTransitions>
  );
}
