import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import { ViewTransitions } from 'next-view-transitions';

import ForceDarkMode from '@/components/auto-theme-switcher';
import PrivyProviderComp from '@/components/providers/privy-provider';
import { ThemeProvider } from '@/components/providers/theme-provider';
import { Toaster } from '@/components/ui/toaster';
import { TooltipProvider } from '@/components/ui/tooltip';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  manifest: '/manifest.webmanifest',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en" suppressHydrationWarning>
        <body className={`${geistSans.variable} ${geistMono.variable} `}>
          <PrivyProviderComp>
            <TooltipProvider>{children}</TooltipProvider>
          </PrivyProviderComp>

          <Toaster />
        </body>
      </html>
    </ViewTransitions>
  );
}
